services:
  - type: web
    name: imageveracity
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python web.py"
    envVars:
      - key: FLASK_ENV
        value: production
