services:
  - type: web
    name: imageveracity
    env: python
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web:app --bind 0.0.0.0:$PORT --workers 2 --timeout 300
    envVars:
      - key: PORT
        value: 10000
